all:
	g++ main.cpp -o main -I /usr/local/include/cryptopp -I /home/rick/include/ -L /home/rick/lib -lboost_serialization -lntl -lgmp -lcryptopp -lm
# aes:
# 	g++ aes.cpp -o test -lntl -lgmp -lm -I /home/rick/include/
