all:
	g++-4.8 main.cpp -o main -lntl -lgmp -lm -lcryptopp -I /home/lyc/include/cryptopp/ -I /home/lyc/ntl/ -L /usr/local/lib -lboost_serialization
aes:
	g++ aes.cpp -o test -lntl -lgmp -lm -I /home/lyc/ntl/
